require:
  - rubocop-rspec
  - ./spec/support/rubocop_patch

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'tmp/**/*.rb'
    - 'vendor/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/ExampleWording:
  Enabled: false

RSpec/FilePath:
  Exclude:
    - 'spec/integration/**/*_spec.rb'

RSpec/HookArgument:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/ClassAndModuleChildren:
  Enabled: false

Style/NestedParenthesizedCalls:
  Exclude:
    - 'spec/**/*.rb'
